name: Package
on:
  push:
    branches:
      - main
    paths:
      - 'FastEndpointsTemplate.nuspec'
jobs:
  publish:
    name: Publish to NuGet.org
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '6.x'

      - name: Create the package
        run: nuget pack FastEndpointsTemplate.nuspec -NoDefaultExcludes

      - name: Publish the package
        run: nuget push *.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_TOKEN}} -SkipDuplicate
