name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup DotNet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      - name: 'Building the API'
        run: dotnet build -c Release
      - name: 'Running Tests'
        run: dotnet test -c Release --no-build --no-restore --nologo
